### ISSUE TITLE
Features:  Nice modularity,  

### ISSUE THREAD

**Issue by fasteddys** [davidfowl/WebApplicationPlugins#2]
Hello, can you add some guidance for plugins

- [ ] how to host/mix Razor pages and MVC views in a plugin 
- [ ] how to handle claims and security in the plugin from the main app
- [ ] what is the model/pattern to use the data access layer, do they have to recreate their own, or will they have access to the main projects data access
- [ ] This suits microservices well, but what is we did not want to fragment the DB, or let all plugins have access to all entities in the DB
- [ ] Theming: is a big pain point in ASP, would be nice to have universal easy todo UI themes.

**Comment by davidfowl** [comment]
>  how to host/mix Razor pages and MVC views in a plugin

This should just work now that views are compiled into the application. Static files are a challenge but its possible to make that work as well. I'll add  a sample with pages.

>  how to handle claims and security in the plugin from the main app

I'm not sure why this is difficult. [This sample](https://github.com/davidfowl/WebApplicationPlugins/blob/fe86d6ec609915ad3331dab62c8a7c688dfd1efb/AuthPlugin/AuthPlugin.cs#L10
) shows how to add an authorization policy in a plugin. Is there something specific you'd like to see?

>  what is the model/pattern to use the data access layer, do they have to recreate their own, or will they have access to the main projects data access

I think that decision is one you need to make. You can do either.

>  This suits microservices well, but what is we did not want to fragment the DB, or let all plugins have access to all entities in the DB

If you're using a single database for all of the services, is it really microservices? I'm not sure it is.

> Theming: is a big pain point in ASP, would be nice to have universal easy todo UI themes.

Agree, that's outside the scope of this sample. See [Orchard.Core](https://docs.orchardcore.net/en/latest/) (the framework pieces, not the CMS). It has a pretty elegant solution for theming.

**Comment by fasteddys** [comment]
> I'm not sure why this is difficult. [This sample](https://github.com/davidfowl/WebApplicationPlugins/blob/fe86d6ec609915ad3331dab62c8a7c688dfd1efb/AuthPlugin/AuthPlugin.cs#L10) shows how to add an authorization policy in a plugin. Is there something specific you'd like to see?

Hello David, let me try to share some context, Currently with the mix of routing and authorization things don't work as easily for developers, after adding MVCrouting + Razor pages, now if we want to add routes to discover pages in a plugin, a) how do we do that & b) more importantly, is there a way to `view the current, routes list/debug all the routes` the program sees/or not seeing. c) when I add RBACattributes or custom claims, from my webproject to the plugin view-controller/page/project its creating a circular ref, I think this might be an easier fix.

Looking at it another way, the upstream and downstream settings in decoupled modules have interdependencies, would be nice to see/visible those across projects/plugins in a cross cutting fashion.

> If you're using a single database for all of the services, is it really microservices? I'm not sure it is.

hmm.. thats not true, there are so many options of new db's, where if the DB is `sharded with with multiple driver instances` then its the same DB on the backend and not the apps responsibility to distribute the data.

**Comment by davidfowl** [comment]
> Looking at it another way, the upstream and downstream settings in decoupled modules have interdependencies, would be nice to see/visible those across projects/plugins in a cross cutting fashion.

What does this have to do with authorization? It sounds like you're asking for lots of things. 

> Currently with the mix of routing and authorization things don't work as easily for developers, after adding MVCrouting + Razor pages, now if we want to add routes to discover pages in a plugin, a) how do we do that.

How do we handle razor pages? You can call AddRazorPages and MapRazorPages in your plugin.

> b) more importantly, is there a way to view the current, routes list/debug all the routes the program sees/or not seeing

Yes you can enumerate the routes that are available to the application.

```C#
app.MapGet("/_plugins", (EndpointDataSource ds) =>
{
    return ds.Endpoints.OfType<RouteEndpoint>().Select(r => r.RoutePattern.RawText);
});
```

You can also get more creative and put each "module" in its own route group and attach metadata about the module itself in endpoint metadata.

> hmm.. thats not true, there are so many options of new db's, where if the DB is sharded with with multiple driver instances then its the same DB on the backend and not the apps responsibility to distribute the data.

As long as schema updates of the service are decoupled from other services and you don't have a single point of failure (like if the db goes down then all the microservices go down) then it's probably fine. I'm not sure many engineering teams are that sophisticated thought.
