### ISSUE TITLE
Applicability to Microservice Chassis pattern?

### ISSUE THREAD

**Issue by PeterKneale** [davidfowl/WebApplicationPlugins#3]
Hi David, 
Thanks for this interesting example.

When writing microservices I find that there is some duplication of code across each repo. I was wondering whether what you've put together here might be applicable to the [microservice chassis approach](https://microservices.io/patterns/microservice-chassis.html). 

ie: 
- Using a single repository/codebase to host a `microservice chassis`. This service would be deployed multiple times, each configured to download a different `microservice plugin` from an s3 bucket / nuget repo etc. It would handle common logging / health checks responsibilities etc.
- Using a repo/codebase per `microservice plugin`. These would be published and then consumed and hosted by the above

I'm not sure whether the the effort. complexity and coupling would be a good tradeoff or if I should stick to using a microservice template and keeping everything nicely isolated. I'd hope an approach like this mean microservice codebases could be simplified to just Application/Domain/Infra assemblies and their associated tests and leave hosting concerns to the to `microservice chassis` / `plugin host`.

Thanks for any advice.

**Comment by InDieTasten** [comment]
If you have recurring code regarding cross-cutting concerns for various service types, I would recommend creating a base/shared service package/project and build the individual service types on top of that using a regular package or project reference.

Dealing with versioning of the chassis vs the individual plugins adds quite a lot of complexity and I don't see any benefit of a plugin solution over a regular dependency on a shared project in this scenario.

The entire plugin pull procedure also adds another point of failure to the system.

**Comment by PeterKneale** [comment]
Cheers - thanks for the feedback
