### ISSUE TITLE
More Generic Naming

### ISSUE THREAD

**Issue by shaggygi** [davidfowl/WebApplicationPlugins#5]
Understanding this is for ASP.NET and probably a prototype/research, but would it be possible to use more generic naming?

I'm using https://github.com/natemcmaster/DotNetCorePlugins to dynamically load in assemblies for a System.CommandLine project.

**Comment by davidfowl** [comment]
I'm not sure what you're asking for?

**Comment by shaggygi** [comment]
Sorry for the lack of details.  I was suggesting to use something else other than `WebApplication` for the namespace.

Would something like `AspNet.Plugin.Extensions` be better (if this project advances)?

Thanks for your work. 👍

**Comment by davidfowl** [comment]
This isn't a package, it's a sample 😄 . You can copy and paste this and make it into whatever you'd like.

**Comment by shaggygi** [comment]
Gotcha 😉 Was thinking it was something in the works for a future feature.  Will keep watch though.  Looks interesting.  Closing out.
